CREATE DATABASE KTL4_KHAC1
USE KTL4_KHAC1
--CÂU 1
--CÂU A
CREATE TABLE NHOMTAISAN
(
	MANHOM CHAR(5)
	CONSTRAINT PK_MN PRIMARY KEY (MANHOM),
	TENNHOM NVARCHAR(50)
)
CREATE TABLE DM_DV_TRUONG
(
	MADV CHAR(2)
	CONSTRAINT PK_MADV PRIMARY KEY (MADV),
	TENDV NVARCHAR(40)
)
CREATE TABLE DM_TAI_SAN
(
	MATAISAN CHAR(5) 
	CONSTRAINT PK_TS PRIMARY KEY (MATAISAN),
	TENTAISAN NVARCHAR (50),
	DONVITINH NVARCHAR(5),
	DONGIA NUMERIC(10,2),
	MANHOM CHAR (5),
	NUOCSX NVARCHAR(50),
	NAMSX DATETIME ,
	CONSTRAINT  FK_MN FOREIGN KEY(MANHOM)
	REFERENCES NHOMTAISAN(MANHOM)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
)

CREATE TABLE TRANG_BI(
	MADV CHAR(2),
	MATAISAN CHAR (5),
	PRIMARY KEY(MADV,MATAISAN),
	NGAYTRANGBI DATETIME,
	SOLUONG INT,
	CONSTRAINT  FK_MADV FOREIGN KEY(MADV)
	REFERENCES dm_dv_truong(MADV)
	ON DELETE CASCADE
	ON UPDATE CASCADE,
	CONSTRAINT  FK_MATAISAN FOREIGN KEY(MATAISAN)
	REFERENCES DM_TAI_SAN(MATAISAN)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)
--CÂU B
ALTER TABLE TRANG_BI
ADD GHICHU NVARCHAR(50)
--CÂU C
ALTER TABLE DM_TAI_SAN
ADD
CONSTRAINT UNQ_TENTS UNIQUE(TENTAISAN),
CONSTRAINT CHECK_DVT CHECK (DONVITINH in(N'CHIẾC',N'BỘ')),
CONSTRAINT CHECK_NAMSX CHECK(YEAR(NAMSX)<YEAR(getdate())),
CONSTRAINT DF_LUONG DEFAULT 0 FOR DONGIA
--CÂU D
INSERT INTO NHOMTAISAN VALUES('LATOP',N'MÁY TÍNH XÁCH TAY')
INSERT INTO NHOMTAISAN VALUES('MACHI',N'MÀN CHIẾU')
INSERT INTO NHOMTAISAN VALUES('MAYIN',N'MÁY IN')
INSERT INTO NHOMTAISAN VALUES('MAYPO',N'MÁY PHOTO COPY')
INSERT INTO NHOMTAISAN VALUES('MAYVP',N'MÁY TÍNH VĂN PHÒNG')
INSERT INTO NHOMTAISAN VALUES('OVERH',N'MÁY CHIẾU OVERHEAD')
INSERT INTO NHOMTAISAN VALUES('PROJT',N'MÁY CHIẾU PROJECTOR')

INSERT INTO DM_DV_TRUONG VALUES('01',N'TRƯỜNG THPT NGUYỄN HUỆ')
INSERT INTO DM_DV_TRUONG VALUES('02',N'TRƯỜNG THPT HUỲNH THÚC KHÁNG')
INSERT INTO DM_DV_TRUONG VALUES('03',N'TRƯỜNG THPT NGÔ GIA TỰ')
INSERT INTO DM_DV_TRUONG VALUES('04',N'TRƯỜNG THPT LÊ LỢI')
INSERT INTO DM_DV_TRUONG VALUES('05',N'TRƯỜNG THPT NGUYỄN THỊ MINH KHAI')

INSERT INTO DM_TAI_SAN VALUES('CANON',N'MÁY IN CANON 1120',N'CHIẾC',2220000,'MAYIN','NHAT BAN','2015-02-13')
INSERT INTO DM_TAI_SAN VALUES('MAYAC',N'MÁY TÍNH ACCER',N'BỘ',4955000,'MAYVP','THAI LAN','2016/03/20')
INSERT INTO DM_TAI_SAN VALUES ('MAYLP',N'MÁY LAPTOP HP',N'CHIẾC' ,13000000,'LATOP','MY','2015/01/11')
INSERT INTO DM_TAI_SAN VALUES ('MAYVP',N'MÁY TÍNH HP',N'BỘ' ,600000,'MAYPO','MY','2015/02/13')
INSERT INTO DM_TAI_SAN VALUES ('MCAUS',N'MÁY CHIẾU',N'CHIẾC' ,1000000,'MACHI','THAI LAN','2016/09/20')
INSERT INTO DM_TAI_SAN VALUES ('POTHP',N'MÁY PHOTO COPY HP',N'CHIẾC' ,50000000,'MAYPO','MY','2014/10/25')
INSERT INTO DM_TAI_SAN VALUES ('PROJE',N'MÁY CHIẾU CANON',N'CHIẾC' ,80000000,'PROJT','NHAT BAN','2015/01/10')

INSERT INTO TRANG_BI VALUES ('01','CANON','2015-05-25' ,4,NULL)
INSERT INTO TRANG_BI VALUES ('01','MAYAC','2016-10-25' ,30,NULL)
INSERT INTO TRANG_BI VALUES ('01','MAYLP','2017-01-02' ,2,NULL)
INSERT INTO TRANG_BI VALUES ('02','MAYAC','2016-10-05' ,20,NULL)
INSERT INTO TRANG_BI VALUES ('02','PROJE','2015-09-20' ,2,NULL)
INSERT INTO TRANG_BI VALUES ('04','MAYLP','2016-11-10' ,3,NULL)
INSERT INTO TRANG_BI VALUES ('04','MAYVP','2016-03-16' ,5,NULL)
INSERT INTO TRANG_BI VALUES ('05','MAYAC','2016-11-25' ,45,NULL)
INSERT INTO TRANG_BI VALUES ('05','MAYLP','2016-12-15' ,5,NULL)
--CÂU 2
--A
CREATE PROC Tang
AS
    UPDATE DM_TAI_SAN
	SET DONGIA = DONGIA*1.05
GO
EXECUTE Tang
--B
UPDATE TRANG_BI
SET GHICHU = case 
WHEN SOLUONG >= 20 then N'CẤP ĐỦ'
ELSE N'CÒN THIẾU'
END
--C
DELETE FROM DM_TAI_SAN
WHERE (YEAR( GETDATE()) -YEAR(NAMSX))>5
--D
SELECT DM_DV_TRUONG.TENDV,DM_TAI_SAN .TENTAISAN,TRANG_BI.SOLUONG,DM_TAI_SAN .DONGIA,(TRANG_BI.SOLUONG*DM_TAI_SAN .DONGIA)AS THANH_TIEN
FROM DM_TAI_SAN ,TRANG_BI ,DM_DV_TRUONG 
WHERE DM_TAI_SAN .MATAISAN=TRANG_BI.MATAISAN AND DM_DV_TRUONG .MADV=TRANG_BI.MADV 
--E
SELECT *
FROM DM_TAI_SAN
WHERE TENTAISAN LIKE (N'MÁY TÍNH%')
--F
SELECT TAISAN1.*
FROM DM_TAI_SAN TAISAN1,DM_TAI_SAN TAISAN2
WHERE TAISAN1.MATAISAN<>TAISAN2.MATAISAN AND (DAY(TAISAN1.NAMSX)=DAY(TAISAN2.NAMSX))
--G
SELECT *
FROM DM_TAI_SAN
WHERE NUOCSX in ('THAI LAN','NHAT BAN')
--H
SELECT *
FROM DM_TAI_SAN
WHERE MATAISAN NOT IN (SELECT MATAISAN FROM TRANG_BI )
--I

--J
SELECT TRANG_BI.MADV,TENDV, COUNT(TRANG_BI.MADV) AS N'SỐ TÀI SẢN'
FROM TRANG_BI,DM_DV_TRUONG
WHERE TRANG_BI.MADV=DM_DV_TRUONG.MADV
GROUP BY TRANG_BI.MADV,TENDV
--K
SELECT TOP 1 WITH ties MATAISAN,TENTAISAN,DONGIA
FROM DM_TAI_SAN
ORDER BY DONGIA DESC
--L
SELECT TENDV,TENTAISAN
FROM TRANG_BI,DM_TAI_SAN,DM_DV_TRUONG
WHERE TRANG_BI.MADV=DM_DV_TRUONG.MADV AND DM_TAI_SAN.MATAISAN=TRANG_BI.MATAISAN AND SOLUONG BETWEEN 2 AND 30
--M
SELECT TRANG_BI.MADV,DM_DV_TRUONG.TENDV,TRANG_BI.SOLUONG
FROM TRANG_BI,DM_DV_TRUONG 
WHERE TRANG_BI.SOLUONG >=15
--CÂU 3
--A
CREATE PROC CHENDULIEU @MADV char(2), @TENDV nvarchar(40)
AS
	BEGIN
		insert into DM_DV_TRUONG(MADV,TENDV)
		values (@MADV,@TENDV)
	END
EXECUTE CHENDULIEU'06',N'CAO ĐẲNG TIỀN GIANG'
--B
GO
 CREATE PROC KETQUA1 @MADV CHAR(2) 
 AS 
	 BEGIN
		SELECT *
		FROM DM_DV_TRUONG, TRANG_BI
		WHERE DM_DV_TRUONG.MADV=TRANG_BI.MADV AND DM_DV_TRUONG.MADV=@MADV
	 END
EXEC KETQUA1 '01'
